### ISSUE TITLE
Error: spawn zip ENOENT

### ISSUE THREAD

**Issue by luisrudge** [importre/electron-starterify#1]
```
λ gulp build
[14:02:48] Using gulpfile c:\git\oss\electron-starterify\gulpfile.js
[14:02:48] Starting 'clean'...
[14:02:48] Finished 'clean' after 42 ms
[14:02:48] Starting 'build'...
[14:02:48] Starting 'browserify'...
[14:02:49] Starting 'copy'...
[14:02:49] Starting 'styles'...
[14:02:49] Finished 'build' after 39 ms
[14:02:49] Finished 'styles' after 56 ms
[14:02:49] Finished 'copy' after 252 ms
[14:02:54] Finished 'browserify' after 5.04 s
[14:02:54] Starting 'release'...
[14:02:54] Finished 'release' after 4.23 ms
[14:02:54] gulp-electron ./dist/app -> electron-starterify\resources\app distributing
[14:02:54] gulp-electron release\v0.25.3\electron-starterify packaging
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn zip ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

I'm on Windows.

**Comment by importre** [comment]
This project depends on https://github.com/mainyaa/gulp-electron.
And `gulp-electron` executes `zip`.
See https://github.com/mainyaa/gulp-electron/blob/v0.0.3/src/index.coffee#L198-L202

Basically there is no `zip.exe` on Windows.
So I've checked on MSYS (`zip` is installed),  it's working.

![msys](https://cloud.githubusercontent.com/assets/1744446/7595963/4226bde8-f925-11e4-9ea6-da4e15c2824b.png)

Thanks for your comment, I'll update `README.md`

**Comment by importre** [comment]
`zip` is not important.
You can zip your output manually :)

**Comment by luisrudge** [comment]
If I remove `darwin`, does that mean that my app will be windows only?

**Comment by importre** [comment]
It's possible if you want.

![screen shot 2015-05-13 at 4 59 16 am](https://cloud.githubusercontent.com/assets/1744446/7597210/e8922dfa-f92c-11e4-8b91-5657c63303e0.png)

Sorry for confusing information.
Updated my comment.

**Comment by luisrudge** [comment]
Great thanks!

**Comment by ingro** [comment]
How did you avoid to create the zip file?

**Comment by importre** [comment]
@ingro, I saw [your comment](https://github.com/mainyaa/gulp-electron/issues/6#issue-76035610).
I agree with you. need some option

I will update the version of `gulp-electron` if the issue is resolved.

Temporarily, run it on `mingw` or `cygwin`.
